format = '''$username$directory
$character'''
add_newline = false

[username]
show_always = true
style_user = "bold green"
format = "[$user]($style) "

[hostname]
ssh_only = false
format = "@$hostname "

[directory]
truncation_length = 0
format = "[$path]($style) "
style = "bold white"

[character]
success_symbol = "> "
error_symbol = "✗ "
